# Generated by Django 2.1.7 on 2019-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('subtype', models.IntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=3000, null=True)),
                ('descr', models.CharField(blank=True, default=None, max_length=6000, null=True)),
                ('connections', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
