# Generated by Django 2.1.7 on 2019-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
