# Generated by Django 2.1.7 on 2019-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exceptions',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
