# Generated by Django 2.1.7 on 2019-03-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_exceptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('addition', models.BooleanField()),
                ('additions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
            ],
        ),
    ]
