# Generated by Django 2.1.7 on 2019-03-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='additions',
            new_name='element',
        ),
    ]
