# Generated by Django 2.1.7 on 2019-03-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190324_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='played_player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='played_player2',
        ),
    ]
