# Generated by Django 2.1.7 on 2019-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190324_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played_player1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='played_player2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_plus',
            field=models.BooleanField(default=False),
        ),
    ]
