# Generated by Django 2.1.7 on 2019-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_game_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coop',
            field=models.IntegerField(default=0),
        ),
    ]
